# Generated by Django 2.2.5 on 2019-09-06 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cedula', models.IntegerField()),
                ('Nombre', models.TextField()),
                ('Fecha', models.DateTimeField()),
                ('Correo', models.TextField(max_length=125)),
                ('Celular', models.IntegerField()),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
    ]
