# Generated by Django 2.2.7 on 2019-11-30 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calendario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Documento', models.IntegerField()),
                ('Nombre', models.TextField()),
                ('FechaCita', models.DateField()),
                ('Horacita', models.CharField(choices=[('0', 'Hora'), ('1', '7:00 am'), ('2', '8:00 am'), ('3', '9:00 am'), ('4', '10:00 am'), ('5', '11:00 am'), ('6', '12:00 pm'), ('7', '1:00 pm'), ('8', '2:00 pm'), ('9', '3:00 pm'), ('10', '4:00 pm'), ('11', '5:00 pm')], default='0', max_length=1)),
                ('Correo', models.TextField(max_length=125)),
                ('Celular', models.BigIntegerField()),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Multas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Documento', models.IntegerField()),
                ('Nombre', models.TextField(max_length=125)),
                ('ValorMulta', models.IntegerField()),
                ('estado', models.BooleanField(default=True)),
                ('FechaMulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendario.Events')),
            ],
        ),
    ]
