# Generated by Django 2.2.5 on 2019-09-12 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='citas',
            old_name='Fecha',
            new_name='FechaCita',
        ),
        migrations.AlterField(
            model_name='citas',
            name='Celular',
            field=models.BigIntegerField(),
        ),
    ]
