# Generated by Django 2.2.6 on 2019-11-13 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Muelitas', '0004_auto_20191004_1034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historial_clinico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Documento', models.BigIntegerField(unique=True)),
                ('Nombre', models.TextField(max_length=125)),
                ('sexo', models.IntegerField(choices=[('1', 'Femenino'), ('2', 'Masculino')], max_length=1)),
                ('fechaNacimiento', models.DateField()),
                ('lugarNacimiento', models.TextField(max_length=125)),
                ('estadoCivil', models.TextField(max_length=125)),
                ('telefono', models.BigIntegerField()),
                ('RH', models.TextField(max_length=125)),
                ('ocupacion', models.TextField(max_length=125)),
                ('motivoConsulta', models.TextField(max_length=200)),
            ],
        ),
    ]
