# Generated by Django 2.2.6 on 2019-11-15 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Muelitas', '0005_historial_clinico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial_clinico',
            name='sexo',
            field=models.CharField(choices=[('1', 'Femenino'), ('2', 'Masculino')], max_length=1),
        ),
    ]
