# Generated by Django 2.2.6 on 2019-11-18 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=45)),
                ('Precio', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('Proveedor', models.CharField(max_length=45)),
            ],
        ),
    ]
